# Generated by Django 2.2.8 on 2020-01-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20200121_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='user',
        ),
    ]
