# Generated by Django 2.2.8 on 2020-01-22 11:28

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_story_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='long_description',
            field=djrichtextfield.models.RichTextField(default='long description', verbose_name='long description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(),
        ),
    ]
