# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    volumes: 
      - ./mysqldb/:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: 'django_project_db'
      MYSQL_ROOT_PASSWORD: 54321